### ISSUE TITLE
send binary?

### ISSUE THREAD

**Issue by reaganry** [lexruee/pi-switch-python#1]
Hi! Is there a way here to  to send a binary code like this? 
switch.send("01001000001010000000010100000000")
thanks!

**Comment by lexruee** [comment]
Hi @reaganry 

The last commit supports this use case: 
https://github.com/lexruee/pi-switch-python/commit/fa8a0b05fd211f96d986a5c8b6bf1a2de6a26a3b

Example usage:
```python
import pi_switch
sender = pi_switch.RCSwitchSender()
sender.enableTransmit(0) # WiringPi pin 0
sender.send("01001000001010000000010100000000")
```

If you can verify if the code above works I'll release new version on the pypi index.

I could only tested this use case here and it works for me:

```python
import pi_switch
sender = pi_switch.RCSwitchSender()
sender.enableTransmit(0) # WiringPi pin 0
sender.sendTriState("0FFF0FFFFFF1") # on
sender.sendTriState("0FFF0FFFFFF0") # off
```

**Comment by reaganry** [comment]
fantastic! let's see.. git clone from the linked commit,  build via sudo python setup.py install...

did it- it worked!! off and on for Stanley brand 433mhz switches. Vielen Dank! 


fyi i have a berner friend michel ruedlinger.. 

reagan

Date: Thu, 29 Jan 2015 13:07:03 -0800

**Comment by lexruee** [comment]
Version 0.2.0 supports sending binary strings and tri-state strings. It's pushed to the pypi index.

@reaganry 
Please feel free to contribute to this project ^^.

Off-topic:
There are some families with Rüdlinger and Rüedlinger names.

A few years ago my father did some research and found out that there is a common root of both family names which dates back to the 18th century.
