### ISSUE TITLE
Installation fails on vanilla Jessie image

### ISSUE THREAD

**Issue by topshed** [lexruee/pi-switch-python#13]
Tries to install on fresh and up-to-date Jessie image. Fails with:

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pi_switch/wrapper/pi_switch.cpp -o build/temp.linux-armv6l-2.7/pi_switch/wrapper/pi_switch.o -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
arm-linux-gnueabihf-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.9/README.Bugs for instructions.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 4

**Comment by divx118** [comment]
Yep, same error for me too. See if we can find something.

**Comment by divx118** [comment]
Ok, fix is simple. Increase the swapfile. By default it is only a 100mb I made mine 1000mb.
The configuration file for swap is located `/etc/dphys-swapfile`, By default it contains 
```
CONF_SWAPSIZE=100
```
The swap file itself is located at `/var/swap` After changing `CONF_SWAPSIZE=100` to something higher, I assume 512 should also be enough, however I used 1000 run 
```
$sudo /etc/init.d/dphys-swapfile stop
$sudo /etc/init.d/dphys-swapfile start
```

**Comment by lexruee** [comment]
@topshed @divx118 Thanks for writing and commenting this issue.
When I have time, I'll try to fix it. 
Maybe this issue can be solved with a modified setup.py file.

**Comment by divx118** [comment]
@lexruee Thanks, that would be nice, if you can't  fix it in the setup.py, maybe spit out a warning that the swap is too small.

BTW off topic thanks for making this available and put your time in it.

**Comment by XpineX** [comment]
Just to let you know, it worked with CONF_SWAPSIZE=512 on an A+
