### ISSUE TITLE
Install script stuck on "cc1plus: warning:"

### ISSUE THREAD

**Issue by abraunton** [lexruee/pi-switch-python#14]
I've followed the instructions to "sudo python setup.py install" but when I run that command I get this;

"cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++" and it just gets stuck and doesn't carry on from there. Any ideas? I'm using a fresh Raspbian installation and have followed the instructions thoroughly.

**Comment by grambas** [comment]
same for me

**Comment by richardtreu** [comment]
Same here

**Comment by GandalfGuenter** [comment]
I've also encountered this problem

**Comment by flori4n** [comment]
`arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pi_switch/wrapper/pi_switch.cpp -o build/temp.linux-armv6l-2.7/pi_switch/wrapper/pi_switch.o -Wno-write-strings

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

arm-linux-gnueabihf-gcc: internal compiler error: Processus arrêté (program cc1plus)

Please submit a full bug report,

with preprocessed source if appropriate.

See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 4

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-JPLgxy/pi-switch/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EHRgJ3-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-JPLgxy/pi-switch
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
osmc@osmc:~$ sudo python send.py -c on -t A -s 11001,10000 -p 0
python: can't open file 'send.py': [Errno 2] No such file or directory`
