### ISSUE TITLE
After raspberry crash and reinstall can't get it working

### ISSUE THREAD

**Issue by Alrd1** [lexruee/pi-switch-python#19]
I used to have the pi_switch working for about half a year, but I had a corrupted SD card.
After reinstalling also followed the reinstallation for the pi_swith, but now my python program does not run.
It gives the following output:

root@pi-desktop:/home/pi/allard/433# python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pi_switch
  File "/usr/local/lib/python2.7/dist-packages/pi_switch/__init__.py", line 1, in <module>
    from _pi_switch import *
ImportError: /usr/local/lib/libwiringPi.so: undefined symbol: crypt
root@pi-desktop:/home/pi/allard/433# sudo python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pi_switch
  File "/usr/local/lib/python2.7/dist-packages/pi_switch/__init__.py", line 1, in <module>
    from _pi_switch import *
ImportError: /usr/local/lib/libwiringPi.so: undefined symbol: crypt

Stripped the complete program test.py
import pi_switch
import time
teller = 0

print "test"

It looks like it failes already at the import pi_switch.

**Comment by lexruee** [comment]
This project is basically dead. I don't intend to fix or matain it in the future.
