### ISSUE TITLE
Can not send decimal

### ISSUE THREAD

**Issue by panagorn** [lexruee/pi-switch-python#7]
Hello, i tried to send decimal with this command :
sender.sendDecimal(1381717, 24) # switch on 
like your example and i get an attribute error saying: RCSwitchSender object has no attribute sendDecimal.
Thank you in advance.

**Comment by lexruee** [comment]
Which version are you using? 

```
pip freeze | grep pi-switch
```


If its below 0.3.0 then you need to upgrade pi_switch:

```
sudo pip install pi_switch --upgrade
```

**Comment by panagorn** [comment]
Thank you. It was version 0.2.0

**Comment by lexruee** [comment]
@panagorn 
Is it working? If so I'll close this issue.
